# Generated by Django 4.1 on 2022-08-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('pass2', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='my_user',
        ),
    ]
